### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by talios** [sviperll/adt4j#16]
I notice that the project can no longer be compiled:

    <parent>
        <groupId>com.github.sviperll</groupId>
        <artifactId>sviperll-maven-parent-6</artifactId>
        <version>3.2-SNAPSHOT</version>
    </parent>

Where can we clone this parent POM to get the required SNAPSHOT, switching to use 3.1 works, but then the project itself fails.

    [ERROR] Failed to execute goal on project adt4j: Could not resolve dependencies for project com.github.sviperll:adt4j:jar:0.15-SNAPSHOT: Could not find artifact
     com.github.sviperll:metachicory:jar:0.19-SNAPSHOT in Nexus (http://nexus.smxemail.com/nexus/content/groups/public/) -> [Help 1]

Cloning the chicory repo ( and changing its parent ) allows everything to compile. Is there anything preventing the parent from being released?

**Comment by sviperll** [comment]
I'll release all required dependencies today. I was trying to setup an infrastructure for javadoc publishing of github.

Would you like new version of adt4j to be released?

**Comment by sviperll** [comment]
All dependencies have been released. HEAD should become buildable now.

**Comment by talios** [comment]
+1 cheers - have there been many changes in ADT4j since 0.14?  I don't have any pressing need for a new release, but was about to explore some additions that would be of use in the near future which is why I was trying to build.

**Comment by jbgi** [comment]
I found that HEAD fails processing when some class the processor explores have a unknown annotation argument (in my case it was XMLType.DEFAULT of the annotation parameter http://docs.oracle.com/javaee/5/api/javax/xml/bind/annotation/XmlType.html#factoryClass%28%29 .)
The exception is thrown at https://github.com/sviperll/chicory/blob/master/metachicory/src/main/java/com/github/sviperll/meta/JCodeModelJavaxLangModelAdapter.java#L546

**Comment by sviperll** [comment]
@jbgi Should be fixed now, check it out?

**Comment by sviperll** [comment]
@talios As of chages...

 * First of all API breaks, it's not backward compatible with 0.14.
 * Equals and CompareTo are implemented without stand-alone visitor-objects. No aditional field is used.
 * Name-arguments for `@Getter`, `@Updater` and `@GeneratePredicate` are now optional

**Comment by talios** [comment]
Nice looking set of changes.  Given API breaks, might I suggest the adoption of SEMVER for versioning the project?  Optional name args for `@Getter` etc. is nice!

**Comment by sviperll** [comment]
Sure I'm going to adopt some flavor of sematic versioning, but this requires 1.0 version to be released and declared stable. Would you like to have it already?

**Comment by jbgi** [comment]
I still have a regression when nesting classes in Visitor interface.
See test case with commit https://github.com/jbgi/adt4j/commit/78fb6ed68672f96b2cd3202ac7325bec1b411bd4

**Comment by sviperll** [comment]
@jbgi, I'm going to declare your example as illegal for now as an instance of some kind of circular dependency.

I have a plan how to fix it, but proper fix requires some time and interaction with jcodemodel project. But this fix will possibly bring your previously much desired [inner-class-visitors](#11) back on the table.

**Comment by jbgi** [comment]
ok. thanks for the hard work!

**Comment by talios** [comment]
With that in mind - maybe cut a 0.14 release then?  The improvements to equals/hashCode sound rather appealing.

**Comment by sviperll** [comment]
1.0 is released! :)

**Comment by talios** [comment]
w00t - looking nice.

**Comment by jbgi** [comment]
congrats and kudos!

**Comment by sviperll** [comment]
@jbgi Your [example](https://github.com/jbgi/adt4j/commit/78fb6ed68672f96b2cd3202ac7325bec1b411bd4) should work now.

**Comment by jbgi** [comment]
Just migrated a project to adt4j 1.1 with great sucess (including nested classes). Thanks!
